import { Header } from "@/components/header"

export const metadata = {
  title: {
    default: "Finance",
    template: '%s | Finance'
  },
  description: "Generated by create next app",
  icons: [
    {
      url: "/logo_blue.svg",
      href: "/logo_blue.svg"
    }
  ]
};

type Props = {
  children: React.ReactNode
}

const DashboardLayout = ({
  children
}: Props) => {
  return (
    <>
      <Header />
      <main className="px-3 lg:px-14">
        {children}
      </main>
    </>
  )
}
export default DashboardLayout